import { motion } from 'framer-motion';
import { Helmet } from 'react-helmet-async';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';

const TermsPage = () => {
  return (
    <>
      <Helmet>
        <title>Terms & Conditions - ShelVey</title>
        <meta name="description" content="Read ShelVey's Terms and Conditions governing your use of our AI-powered business automation platform." />
      </Helmet>

      <div className="min-h-screen bg-background">
        <Navbar />

        <main className="pt-24 pb-16">
          <div className="container mx-auto px-4 py-16 max-w-4xl">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <h1 className="text-4xl font-cyber font-bold mb-8 text-gradient">Terms & Conditions</h1>
              <p className="text-muted-foreground mb-8">Last updated: December 5, 2025</p>

              <div className="prose prose-invert max-w-none space-y-8">
                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">1. Acceptance of Terms</h2>
                  <p className="text-muted-foreground">
                    By accessing or using ShelVey's services, you agree to be bound by these Terms and Conditions. 
                    If you do not agree to these terms, please do not use our services. ShelVey, LLC ("Company," "we," "our") 
                    provides AI-powered business automation services subject to your compliance with these terms.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">2. Services Description</h2>
                  <p className="text-muted-foreground">
                    ShelVey provides AI agent services for business automation, including but not limited to market research, 
                    brand development, content creation, website generation, and marketing automation. Our services are designed 
                    to assist in business building and are provided on an "as-is" basis.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">3. User Accounts</h2>
                  <p className="text-muted-foreground">
                    You must create an account to access our services. You are responsible for maintaining the confidentiality 
                    of your account credentials and for all activities under your account. You must provide accurate and complete 
                    information when creating your account and keep it updated.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">4. Subscription and Payments</h2>
                  <p className="text-muted-foreground">
                    Our services require a paid subscription. Subscription fees are billed in advance on a monthly basis. 
                    All fees are non-refundable except as required by law. We reserve the right to change pricing with 30 days' notice. 
                    Failure to pay may result in suspension or termination of services.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">5. Acceptable Use</h2>
                  <p className="text-muted-foreground mb-4">You agree not to use our services to:</p>
                  <ul className="list-disc list-inside text-muted-foreground space-y-2">
                    <li>Violate any applicable laws or regulations</li>
                    <li>Infringe on intellectual property rights of others</li>
                    <li>Generate fraudulent, misleading, or harmful content</li>
                    <li>Attempt to gain unauthorized access to our systems</li>
                    <li>Interfere with the proper functioning of our services</li>
                    <li>Use automated systems to abuse our services</li>
                  </ul>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">6. Intellectual Property</h2>
                  <p className="text-muted-foreground">
                    Content generated by our AI agents on your behalf becomes your property upon payment. However, ShelVey 
                    retains ownership of all proprietary technology, algorithms, and systems. You grant us a license to use 
                    aggregated, anonymized data to improve our services.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">7. Limitation of Liability</h2>
                  <p className="text-muted-foreground">
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW, SHELVEY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
                    SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID 
                    BY YOU IN THE TWELVE MONTHS PRECEDING THE CLAIM.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">8. Termination</h2>
                  <p className="text-muted-foreground">
                    Either party may terminate this agreement at any time. Upon termination, your right to use our services 
                    ceases immediately. We may retain certain data as required by law or for legitimate business purposes.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">9. Governing Law</h2>
                  <p className="text-muted-foreground">
                    These terms shall be governed by the laws of the State of Delaware, United States. Any disputes shall 
                    be resolved in the courts of Delaware.
                  </p>
                </section>

                <section className="glass-morphism cyber-border p-6 rounded-xl">
                  <h2 className="text-xl font-cyber font-bold mb-4 text-foreground">10. Contact Information</h2>
                  <p className="text-muted-foreground">
                    For questions about these Terms, please contact us at:<br />
                    <strong>ShelVey, LLC</strong><br />
                    131 Continental Dr Suite 305<br />
                    Newark, DE, 19713 US<br />
                    Email: admin@shelvey.pro
                  </p>
                </section>
              </div>
            </motion.div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default TermsPage;
